<?php $forms = array( "NPS"   => array('fullName',
                                        'post',
                                        'dept',
                                        'dob',
                                        'dateOfJoin',
                                        'Bpay',
                                        'NomName1',
                                        'NomDOB1',
                                        'NomPShr1',
                                        'NomRel1',
                                        'NomName2',
                                        'NomDOB2',
                                        'NomPShr2',
                                        'NomRel2',
                                        'NomName3',
                                        'NomDOB3',
                                        'NomPShr3',
                                        'NomRel3',
                                        'EarNomDate',
                                        'NomDay',
                                        'NomMonth',
                                        'NomYear',
                                        'NomPlace',
                                        'WitnessName1',
                                        'WitnessAddr1',
                                        'WitnessName2',
                                        'WitnessAddr2',
                                        'EmpNo'
                                      ),
                          "I_Card" => array(    'fullName',
                                                'EmpNo',
                                                'post',
                                                'dept',
                                                'dob',
                                                'bloodgrp',
                                                'AddrLine1',
                                                'AddrLine2',
                                                'AddrLine3',
                                                'contactNo',
                                                'EmercontactNo',
                                                'TodayDate'
                          ),
                          "IITP_CLUB" => array( 'fullName',
                                              'post',
                                              'dept',
                                              'dob',
                                              'AddrLine1',
                                              'contactNo',
                                              'dateOfJoin',
                                              'withEffectFrom',
                                              'TodayDate')
                   )  ?>
<?php $placeholders  = array('fullName'=> '+++fullName+++',
                              'post'=> '+++post+++',
                              'dept'=> '+++dept+++',
                              'dob'=> '+++dob+++',
                              'bloodgrp' => '+++bloodgrp+++',
                              'TodayDate' => '+++TodayDate+++',
                              'EmercontactNo'=> '+++EmercontactNo+++',
                              'contactNo' => '+++contactNo+++',
                              'dateOfJoin'=> '+++dateOfJoin+++',
                              'AddrLine1' => '+++AddrLine1+++',
                              'AddrLine2' => '+++AddrLine2+++',
                              'AddrLine3' => '+++AddrLine3+++',
                              'withEffectFrom' => '+++withEffectFrom+++',
                              'Bpay'=> '+++Bpay+++',
                              'NomName1'=> '+++NomName1+++',
                              'NomDOB1'=> '+++NomDOB1+++',
                              'NomPShr1'=> '+++NomPShr1+++',
                              'NomRel1'=>   '+++NomRel1+++',
                              'NomName2'=> '+++NomName2+++',
                              'NomDOB2'=> '+++NomDOB2+++',
                              'NomPShr2'=> '+++NomPShr2+++',
                              'NomRel2'=>'+++NomRel2+++',
                              'NomName3'=> '+++NomName3+++',
                              'NomDOB3'=> '+++NomDOB3+++',
                              'NomPShr3'=>'+++NomPShr3+++',
                              'NomRel3'=>'+++NomRel3+++',
                              'EarNomDate'=> '+++EarNomDate+++',
                              'NomDay'=>'+++NomDay+++',
                              'NomMonth'=>'+++NomMonth+++',
                              'NomYear'=>'+++NomYear+++',
                              'NomPlace'=>'+++NomPlace+++',
                              'WitnessName1'=> '+++WitnessName1+++',
                              'WitnessAddr1'=> '+++WitnessAddr1+++',
                              'WitnessName2'=> '+++WitnessName2+++',
                              'WitnessAddr2'=> '+++WitnessAddr2+++',
                              'EmpNo'=> '+++EmpNo+++'
                            ); ?>
